name: Update Course Data

on:
  schedule:
    - cron: '0 0 * * 0' # Runs every Sunday at midnight
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  fetch-and-update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Create the groups directory if it doesn't exist
      run: mkdir -p groups

    - name: Fetch the course data
      run: curl https://edt.univ-nantes.fr/sciences/g350604.xml -o groups/350604.table

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Actions"
        git add groups/350604.table
        git commit -m "Update course data" -a || echo "No changes to commit"
        git remote set-url origin https://timecube-ascii:${{ secrets.MY_PAT }}@github.com/timecube-ascii/timecube-ascii.github.io.git
        git push

