name: Update Course Data

on:
  schedule:
    - cron: '0 0 * * 0' # Runs every Sunday at midnight
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  fetch-and-update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get install -y jq curl

    - name: Create necessary directories
      run: |
        mkdir -p groups
        mkdir -p logs

    - name: Fetch and update course data with logging
      run: |
        log_file="logs/update_log_$(date +'%Y-%m-%d').log"
        jq -r '.[] | to_entries[] | "\(.key) \(.value)"' timetable.json | while read -r course_code url_id; do
          echo "Processing course: $course_code" | tee -a $log_file
          if curl -s "https://edt.univ-nantes.fr/sciences/${url_id}.xml" -o "groups/${course_code}.table"; then
            echo "[$(date +'%Y-%m-%d %H:%M:%S')] Update successful for $course_code" | tee -a $log_file
          else
            echo "[$(date +'%Y-%m-%d %H:%M:%S')] Update failed for $course_code" | tee -a $log_file
          fi
        done

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Actions"
        git add groups/* logs/*
        git commit -m "Update course data and log results" -a || echo "No changes to commit"
        git remote set-url origin https://timecube-ascii:${{ secrets.MY_PAT }}@github.com/timecube-ascii/timecube-ascii.github.io.git
        git push
